### ISSUE TITLE
'fc1' outgoing_weights are getting reset https://github.com/timoklein/redo/blob/main/src/redo.py#L120

### ISSUE THREAD

**Issue by SaminYeasar** [timoklein/redo#3]
`fc1` has (3136,512) params and it seems like current implementation always `resets` and `sets 0` to the dead-neuron for out-going layer-512. The implementation is supposed to `reset` the dead-neurons of the `incoming-layer` and `set 0` the dead-neuron of the `outgoing-layers`. [https://github.com/timoklein/redo/blob/main/src/redo.py#L120](https://github.com/timoklein/redo/blob/main/src/redo.py#L120)

**Comment by timoklein** [comment]
I'm not quite sure I got you correctly but let me try to explain:

1.  I have a mask for the activations of `fc1` of shape $(512, )$.
2. The ingoing weights of my neuron are thus defined by `fc1` and I can select and re-initialize them with `fc1.weight.data[:, mask]`.
3. The outgoing weights of my neuron are in `q`, which is of shape $(512, 6)$. Here, I can select the outgoing weights with `q.weight.data[mask, :]` and set them to zero.

The code on the new branch does that, please see here
https://github.com/timoklein/redo/blob/6fbd0c3939de13e60a173547f7ce452f00aa151a/src/redo.py#L109-L137

I have fixed everything except the moment-resets on that branch, please refer to it.

**Comment by SaminYeasar** [comment]
I just rechecked. I believe the `reset` of the `incoming-weights` is fine. There's an error when the code tries to set zero at the `outgoing layer` at this step [https://github.com/timoklein/redo/blob/main/src/redo.py#L135](https://github.com/timoklein/redo/blob/main/src/redo.py#L135)  `conv3 (64,64,3,3)` to `fc1 (3136,512)`. Here activation-dim is `64` that needs to match the dimension of `out-going layer`: `3136`. `next_layer.weight.data` basically transposes the matrix to `(512, 3136)`, hence, the current implementation sets 0 to the `incoming layer` instead. The following code should fix this. Let me know if you think this is wrong. Thanks.

``` 
num_repeatition = next_layer.weight.data.shape[1] // mask.shape[0]
linear_mask = torch.repeat_interleave(mask, num_repeatition)
next_layer.weight.data[ : , linear_mask] = 0.0
```

**Comment by timoklein** [comment]
> The following code should fix this. Let me know if you think this is wrong. Thanks.

No, this is actually correct. Good catch. I'll fix this and run some experiments to verify it. It must also be fixed for the outgoing weight bias resets here:

https://github.com/timoklein/redo/blob/7069e9f27b2d1087f6ae20fd4a0aba80b9e5fc9d/src/redo.py#L163-L172

It's quite interesting that the wrong resets are already improving performance substantially

**Comment by timoklein** [comment]
Closing this as it's implemented in https://github.com/timoklein/redo/pull/2.
