### ISSUE TITLE
implementation of the mask to random initialize weights

### ISSUE THREAD

**Issue by SaminYeasar** [timoklein/redo#4]
The flat-mask (`ex: (32,)`) from dead_neurons gets repeated to make the mask 4D shape of the conv-net ( `ex: (8,8,4,32)` ) here: [https://github.com/google/dopamine/blob/master/dopamine/labs/redo/weight_recyclers.py#L652](https://github.com/google/dopamine/blob/master/dopamine/labs/redo/weight_recyclers.py#L652). does the following initialization have the same effect? : [https://github.com/timoklein/redo/blob/main/src/redo.py#L17](https://github.com/timoklein/redo/blob/main/src/redo.py#L17)

**Comment by timoklein** [comment]
Hope I understood your question correctly: Yes. I'm using broadcasting to just select the rest of the weight matrix based on the flat mask.
