### ISSUE TITLE
About the official ReDO implementation

### ISSUE THREAD

**Issue by Zarzard** [timoklein/redo#7]
Hello Timo,

I was trying to run the official ReDO code but got [this error](https://github.com/google/dopamine/issues/223). I wonder if you have encountered this before. Thanks!

**Comment by timoklein** [comment]
Hi there,

I ran the official code a while back to check the evolution of dead neurons over time and didn't have any issues back then. Seems like you fixed the issue anyway? I'm not very familiar with JAX (yet), so I can't help much with JAX-specific issues.

**Comment by Zarzard** [comment]
@timoklein I see. Thank you for your reply!
